### PR TITLE
Bug: fix driver ride index page logic layer service connection.

### PR DESCRIPTION
**Pull request by RichardVSaasbook**
# Bug Fixes
+ Fix connection on driver ride index page

### CODE REVIEW

**Comment by RichardVSaasbook** [comment]
Ready to merge.

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
fix conflict.

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
new conflicts.

**Comment by RichardVSaasbook** [comment]
Conflict resolved.

**Review by ghost — APPROVED** [review]

**Pull request merged**
