### PR TITLE
Chore: cleanup the interface

### PR DESCRIPTION
**Pull request by RichardVSaasbook**
# New Features
+ Logo instead of text in header
+ Page footer

# Bug Fixes
+ Hide menu button when above 992 pixels
+ Hookup logout link to the logic layer service
+ Add scrollbars to sidebar and main content if they cannot fit on the screen

### CODE REVIEW

**Comment by RichardVSaasbook** [comment]
Ready to merge.

**Comment by RichardVSaasbook** [comment]
Actually ready to merge now.

**Review by ghost — CHANGES_REQUESTED** [review]
fix the conflicts.

**Comment by RichardVSaasbook** [comment]
Conflicts resolved.

**Review by ghost — APPROVED** [review]

**Pull request merged**
